services:
  taiko-web-redirect:
    image: arbarwings/docker-web-redirect:latest
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.R5.rule=Host(`taiko-web-is-4ever.yuuk1.tk`) || Host(`taiko-web-v2.yuuk1.tk`)
      - traefik.http.routers.R5.entryPoints=websecure
      - traefik.http.routers.R5.tls=true
      - traefik.http.routers.R5.tls.certResolver=letsencrypt
      - traefik.http.routers.R5.service=S5
      - traefik.http.services.S5.loadbalancer.server.port=80
    environment:
      - REDIRECT_TARGET=taikoapp.uk

networks:
  traefik:
    external: true
    name: traefik
