services:
  litey-redis:
    volumes:
      - ./redis:/data
    image: redis:latest
  litey:
    image: ghcr.io/yuukiwww/litey:latest
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.R4.rule=Host(`litey.trade`)
      - traefik.http.routers.R4.entryPoints=websecure
      - traefik.http.routers.R4.tls=true
      - traefik.http.routers.R4.tls.certResolver=letsencrypt
      - traefik.http.routers.R4.tls.domains[0].main=litey.trade
      - traefik.http.routers.R4.tls.domains[0].sans=*.litey.trade
      - traefik.http.routers.R4.service=S4
      - traefik.http.services.S4.loadbalancer.server.port=8000
    environment:
      - MONGO_URI=mongodb+srv://cluster0.xwewvby.mongodb.net/
      - MONGO_USER=yuuki
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - REDIS_URI=redis://litey-redis:6379/

networks:
  traefik:
    external: true
    name: traefik
